config/routes.rb
Rails.application.routes.draw do
  resources :slices
  get '/ping/:uuid' => 'slices#ping'
  get '/cut/:uuid' => 'slices#cut', as: :cut
  put '/slot/:id/tag/:tag' => 'slices#tag', as: :tag
  get '/week/:uuid(/:week_no)' => 'slices#week', as: :week

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/slice.rb
class Slice < ApplicationRecord

  TIME_PERIOD = 2.minute
  scope :from_date, ->(date){ where("timestamp >= ?", date.to_time.to_i).where("timestamp < ?", (date+1).to_time.to_i) }
  scope :from_user, ->(user_hash){ where(user_hash: user_hash) }
  scope :working, ->(worth = 1){where(worth: worth)}

  def time
    Time.zone.at(self.timestamp)
  end

  def time=(val)
    case val
    when String
      val = Time.parse(val)
    when Time
      val = val
    when Date
      val = val.to_time
    end
    self.timestamp = val.to_i
  end

  def self.ping(user_hash)
    time = Time.zone.now
    last_slice  = from_date(time.to_date).working.from_user(user_hash).order(timestamp: 'desc').first
    if last_slice.nil?
      #start_of_the_day
      create(time: time-1, user_hash: user_hash, worth:1, desc: 'start of the day')
      # first slice
      create(time: time, user_hash: user_hash, worth:1, desc: 'work')
    elsif last_slice.time > time - TIME_PERIOD
      last_slice.update(time: time)
    else
      create(time: time-1, user_hash: user_hash, worth: 0, desc: nil) unless last_slice.time < time.to_date
      create(time: time,  user_hash: user_hash, worth: 1, desc: 'work')
    end
  end

  def self.cut(user_hash)
    time = Time.zone.now
    last_slice  = from_date(time.to_date).working.from_user(user_hash).order(timestamp: 'desc').first
    create(time: time,  user_hash: user_hash, worth: last_slice.worth, desc: last_slice.desc )
  end

  def self.to_slots
    last_slice = nil
    slots = self.order(timestamp: :asc).map do |slice|
      if last_slice.nil?
        last_slice = slice
        next
      end
      time = slice.timestamp-last_slice.timestamp
      slot = {
        start: last_slice.time,
        close: slice.time,
        time: human_time(time),
        percent: percent(time),
        worth: slice.worth,
        id: slice.id,
        desc: slice.desc,
        title: "#{last_slice.time.strftime("%I:%M%p")} - #{slice.time.strftime("%I:%M%p")} <br> #{human_time(time)} -> #{slice.desc}"
      }
      last_slice = slice
      slot
    end

    slots.compact
  end

  def self.to_time
    all_slice = self.order(timestamp: :asc)
    return 0 unless all_slice.count > 2

    break_time = all_slice.where(worth: 0).map do |close_slice|
      start_slice = all_slice.where("timestamp < ?",close_slice.timestamp ).last
      close_slice.timestamp - start_slice.timestamp
    end
    break_time = break_time.inject(&:+)
    self.all.last.timestamp.to_i - self.all.first.timestamp.to_i - break_time.to_i
  end

  def self.percent(time)
    [time/432, 0.3].max
  end

  def self.human_time(sec)
    seconds = sec % 60
    minutes = (sec / 60) % 60
    hours = sec / (60 * 60)

    format("%02d:%02d:%02d", hours, minutes, seconds)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/slices_controller.rb
class SlicesController < ApplicationController
  before_action :set_slice, only: [:show, :edit, :update, :destroy, :tag]

  # GET /slices
  # GET /slices.json
  def index
    @slices = Slice.all
  end

  # GET /slices/1
  # GET /slices/1.json
  def show
  end

  # GET /slices/new
  def new
    @slice = Slice.new
  end

  # GET /slices/1/edit
  def edit
  end

  # POST /slices
  # POST /slices.json
  def create
    @slice = Slice.new(slice_params)

    respond_to do |format|
      if @slice.save
        format.html { redirect_to @slice, notice: 'Slice was successfully created.' }
        format.json { render :show, status: :created, location: @slice }
      else
        format.html { render :new }
        format.json { render json: @slice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /slices/1
  # PATCH/PUT /slices/1.json
  def update
    respond_to do |format|
      if @slice.update(slice_params)
        format.html { redirect_to @slice, notice: 'Slice was successfully updated.' }
        format.json { render :show, status: :ok, location: @slice }
      else
        format.html { render :edit }
        format.json { render json: @slice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /slices/1
  # DELETE /slices/1.json
  def destroy
    @slice.destroy
    respond_to do |format|
      format.html { redirect_to slices_url, notice: 'Slice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def ping
    Slice.ping(params[:uuid])
    render body: nil
  end

  def cut
    Slice.cut(params[:uuid])
    redirect_to week_path(params[:uuid])
  end

  def week
    @user_hash = params[:uuid]
    @active_week = params[:week_no].nil? || params[:week_no] == Time.zone.now.to_date.strftime("%U")
    Slice.ping(@user_hash) if params[:ping]
    @week_no = params[:week_no] || Time.zone.now.to_date.strftime("%U")
    now = Date.today
    monday = Date.commercial(now.cwyear,@week_no.to_i)
    @week_time = 0
    @week = (0..4).map do |d|
      date = (monday + d)
      timestamp = Slice.from_date(date).from_user(@user_hash).to_time
      @week_time += timestamp
      {
        date: date,
        slots: Slice.from_date(date).from_user(@user_hash).to_slots,
        time: Slice.human_time(timestamp),
        timestamp: Slice.human_time(timestamp)
      }
    end
    @week_time = Slice.human_time(@week_time)
  end

  def tag
    @slice.update(desc: params[:tag])
    user_hash = @slice.user_hash
    if params[:tag] == 'lunch'
      @slice.update(worth: 0)
      date = @slice.time.to_date
      slots = Slice.from_date(date).from_user(user_hash).where(worth: 0).where("id != ?", @slice.id).where("desc != ? OR desc IS NULL", 'lunch')
      # return render json: Slice.from_date(date).from_user(user_hash).where(worth: 0).where("id != ?", @slice.id).where("desc != ? OR desc is null", 'lunch').map(&:desc)
      slots.update_all(worth: 1, desc: 'Pipi break')
    end
    redirect_to week_path(@slice.user_hash)
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_slice
      @slice = Slice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def slice_params
      params.require(:slice).permit(:time, :user_hash, :desc, :worth)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/slices_helper.rb
module SlicesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Copper</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <div class="push-down-60">
      <%= yield %>
    </div>
  </div>


</body>
</html>

app/views/slices/_day.html.slim
.progress
  -slots.each do |slot|
    div
      / = slot.to_s
    .progress-bar.has-tooltip[data-toggle="tooltip" data-html="true" style="width: #{slot[:percent]}%" title=slot[:title] class=((slot[:worth].to_i != 1) ? 'progress-bar-warning progress-bar-striped active' : ((slot[:desc] != 'work') ? 'progress-bar-success' : ''))]
      small
        strong
          - if display_link
            = link_to slot[:time], tag_path(slot[:id], 'lunch'), method: :put
          - else
            = slot[:time]

app/views/slices/_form.html.slim
= form_for @slice do |f|
  - if @slice.errors.any?
    #error_explanation
      h2 = "#{pluralize(@slice.errors.count, "error")} prohibited this slice from being saved:"
      ul
        - @slice.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :time
    = f.text_field :time
  .field
    = f.label :user_hash
    = f.text_field :user_hash
  .field
    = f.label :desc
    = f.text_area :desc
  .field
    = f.label :worth
    = f.number_field :worth
  .actions = f.submit

app/views/slices/edit.html.slim
h1 Editing slice

== render 'form'

= link_to 'Show', @slice
'  |
= link_to 'Back', slices_path

app/views/slices/index.html.slim
h1 Listing slices

table
  thead
    tr
      th Time
      th User hash
      th Desc
      th Worth
      th
      th
      th

  tbody
    - @slices.each do |slice|
      tr
        td = slice.time
        td = slice.user_hash
        td = slice.desc
        td = slice.worth
        td = link_to 'Show', slice
        td = link_to 'Edit', edit_slice_path(slice)
        td = link_to 'Destroy', slice, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Slice', new_slice_path

app/views/slices/new.html.slim
h1 New slice

== render 'form'

= link_to 'Back', slices_path

app/views/slices/show.html.slim
p#notice = notice

p
  strong Time:
  = @slice.time
p
  strong User hash:
  = @slice.user_hash
p
  strong Desc:
  = @slice.desc
p
  strong Worth:
  = @slice.worth

= link_to 'Edit', edit_slice_path(@slice)
'  |
= link_to 'Back', slices_path

app/views/slices/week.html.slim
h1
  | Week &nbsp;
  = @week_no

.meta
  = link_to "← #{ @week_no.to_i-1}", week_path(@user_hash, @week_no.to_i-1)
  = link_to "#{ @week_no.to_i+1} →", week_path(@user_hash, @week_no.to_i+1), class: 'pull-right'
br

- @week.each do |day|
  div
    strong = day[:date]
    strong.pull-right = day[:time]
  = render 'day', slots: day[:slots], display_link: @active_week

- if @active_week
  hr
  .row
    = link_to 'cut now', cut_path(@user_hash), class: 'col-sm-4 col-sm-offset-4 btn text-center btn-primary'
  hr

br
h3 = @week_time